version: '3.9'
services:
  app:
    container_name: portfolio
    build:
      context: .
      # target: development
    command: serve -s build
    volumes:
      - './src:/app/src'
    ports:
      - 3001:3001
    environment:
      HREACT_APP_API_ENDPOINT: "${REACT_APP_API_ENDPOINT}"
      REACT_APP_HOST_ENV: "${REACT_APP_HOST_ENV}"
      NODE_ENV: "${NODE_ENV}"
      PORT: "${PORT}"
