version: '3.9'

services:

  app:
    container_name: portfolio
    build:
      context: .
      # target: development
    volumes:
      - './src:/app/src'
    ports:
      - 8050:3000
    environment:
      HOST: "${HOST}"

